apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: auth-api
  namespace: api
spec:
  chart:
    spec:
      chart: auth-api
      sourceRef:
        kind: HelmRepository
        name: auth-api
        namespace: flux-system
      version: 0.1.x
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  releaseName: auth-api
  values:
    image:
      tag: latest