apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: 1.16.x
  interval: 1h0m0s
  releaseName: cert-manager
  values:
    crds:
      enabled: true
      keep: true
    prometheus:
      enabled: false
    ingressShim:
      defaultIssuerName: letsencrypt
      defaultIssuerKind: ClusterIssuer
