apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vpa
  namespace: kube-system
spec:
  chart:
    spec:
      chart: vpa
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      version: 4.7.x
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  releaseName: vpa
