---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: p2p-api-env-secret
  namespace: api
spec:
  encryptedData:
    JWT_SECRET: AgDIT6DRa/PZCm71mUX2jdrSf/iA8EcreBikaJMi56oCDecfW28vtQoVI9bg6DG3z5bfop7Ua0qdgQCqfJhSEy6Q79qay+efbidXoLGA/eej83ObTfr6sRU8EZxiPcn8qdRfNF8guR52WgnRDc6Is8YsbXAChEh8y7RDM8rqIjIKcsLhS7i+q0KbO4+gVqdBXZDS3aRl/Da9OFqTGXsjs5/jQ20yFl1UqxEqwfrplckNQEBq1vIYF5+hu9FAJ1aikvyhur3yQakBqglbM8m88hjBEW4FNFgUgtnLJyEPzXUJOUQmZJ8MghLX4IY59z5Gh25IrZG9MKpwvmxuv2J/wlFoFTzbk8H6hcWmVMv+i2cNKS9KZoVi02iXOS9m3vpf4UZqCySEY/CfcQquvwpbXktusHRfT5EbIeOdDacdS+X46g3KUQNlP4kU0K2w3L7S6OaoC+gHfSSiGsWXJlt0mauehwTwiugwx5zGpwt3ZG8Ic7Mk4jHZcPOrE/Yvnp9SwURxESTS4ge4hQiXnSDTM1qt42Z5/S33boKG9hKKXoXjOk3lhBV2qoXYlGT2mG8Wt9pzQ5dzUecNZRz4+mP+pK0ZDynJSyZgOOOFPCq3WFhLG1ZgIr6saPZ0R+0b/YpvJOyXrgE+Q8l4S0F88fj727GmCZ4c+PWe/Yq4hwm3hbXWkKZcWtl4Yl1SbAuejvWgulTOaZrgoahEDzKDAji6pwumIXmlB66ujIHUvaoMZmajyK623pycFklQ5fa1g30xjoK2+0tDtLzHk6xXkC2PCTamdVHLC9xd6T9rEx2QdI2P5NzPYEqMIj/rIM11VdYV30uTpk1X7Sad/IIHCLJnobZCdi2MEx8yRWmCJLJ7i9N/pGUOH2eL+hU0Sd050J3VG0hTwNW0aEum2t83piZJC0oxcxCW3V/P+CeCmP/leqWjE4ROe6pmkbtVO87m4dR1EgbJNGlrH2+oiccg5UMRNy1EhsPQWtHYGcK8udwOpl8Tpwr+HCrHKSp2kV6UiCIypVTVx6tcBK2kFB4UBRcdINFC4/BEpFRV+Og8qdEUuYO5vFHPvckg8v7SJq/HlS2cQgRQwlbbETEJlz3fA400B3lSP2pH9dO62stf6GUEq8P0MtY6LIn5Z0nPmcNHTwMVKUsMwJlgHhoDRQ==
  template:
    metadata:
      creationTimestamp: null
      name: p2p-api-env-secret
      namespace: api
