---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: p2p-api-env-secret
  namespace: api
spec:
  encryptedData:
    JWT_SECRET: AgB5QXfLjtqY79Drfs6Rn1V/vpJvihuUf6h6M0oFFsjhV2PpXJ39UzWk1OWlqPDegYD85r0IZ7fQ8Tw7GJ4jORclmUaBJe96I7DPSShBOL5YlgpvOannfRJ5nVgOnmIQrFTkokGtxst4hsSIXh7KZc5EIotf5g2PY2R+m5Y3YxHu/hyR33CvCww6HHQyy/P5RkoCreRysaBjkuha4A/Yz5AatedHhfcO6wR2/sztbGpBpqLG0MnbI/iR2b4hYhBSJEmzdaq/U7ilPma13TTV2RB3QnU6SFihB5YO94FaBuZzNaqIJV4tmsD/gX4IMILiQe7EG5QFBjZ6HnRwRQGkvekUmp9DS1RRVPyQT7yb44X7riThst9AGaCNSPKYCoJIARcmFtVoF6VU/3Xudsp97ZDfOeAIvfTsST1aMqcKiTxxzAlzDY1OiNYTiMvwGsRNWOl6tndDEKUrzsvDObNCr8EvsypCQaV/BmI2+tHUk9rZwMP0DKAfZmiEXj2Kt7szIoUOZXGymmLexJhgjFz5iz/i3QDFhA1SWdwp5BQdaqqs10gJf0fXkGk4RfzcPSXEmqUv6Jh5MGlXpmIQL/hJONGgwW8etPpMj5yB25UA1pVHUqgLnV+VDIwxj0tYlovoIOJiLPQuaF7iLNN6Wh8LeRV+Txc/k+YRLgGmp6Hwrxk2BspYZJqtBs5Slsag/fDHuiiBxqie7+e5i/Wu0KCzGijoB4sQFR2J3SKTO3xI+Nk2iRhhM3UfHoWy0Km8GEbHAA1Ve1RjM+Wq0c71O1/0Eqj97Ul4+cdRJQWvi6e7JTAmRdghJffGNAi1JYaStxI8xeDlQaFlnmSg1FmuaUsTcmdKXPcP0Eo+zrxUq1XE1JuKJ7eb1Bqh1Wj7u/ONKAanlIGoDCQSOmbz7OlzfyE7x9/T+qKo67V3TC0BO5/3v+qBqh4U0hl07CoW4+A4zohSNe8IsAFGbqPQIpjsz507hbwhrS1a//48AqiiCoHFUhBWQB1V2VQTFpPHBqMk3/T2VUakEc2ujmpDC+4dVOtDfl08F54/eJnziHmUlSh6lhqVa0JOO4Uw46J5x8DhFtOWi0me6UONGLr4o+LWTb7+8RwhsJnj/oDp1M9g8bPc+JuaJ0L0w/8YzuQ8cP1HugVNU6uxT8HfQLPobQ==
  template:
    metadata:
      creationTimestamp: null
      name: p2p-api-env-secret
      namespace: api
