---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: p2p-api-env-secret
  namespace: api
spec:
  encryptedData:
    JWT_SECRET: AgCZh8vdqoQF1KHEHK8WSukf016saB8SMRsu182b7+9Vi6lAXvFqszbAWmJJm6qg5QisM29PTq97T+/uCVshZuG24/YC6CPZQASeHCQgy4uN6lEE6YznOZtaEH+SF3ylEcsX4mnqWOtCCq60fzfrVov9tQ9UJJ5dA26yjMmaPs/QdPii2qUACG9wAiAv2iG6vXepXrWPYizPOQMv8czIizhhwDyqtkXavR7F2+KFYzSmmHFEijqeOLwNdkmVZCLVsqrGU/uxGaNBIQfdO1QJGulaGkmOIxtqqlLEy5/vg71R/s4KMV950HoFC7xGYyRuOkUl3tvrXronBmsWdpPZzCbTDry8gM+uC5/ce3Ufel92WrBC7FqKxopLaqM1FMoPPf12jerArHwkMNoSQaOPNN/deYTNobkmqErPSzaw+lABfGGtATDtDJ3NgItBe5vY8VLQmexzbkRaUriRH2aebKxwSdkp/xfVE3yTPc1U6B388EX6jrwJHsagj0UQ2gXvYghweW30qBfD5aDNHnhFObuOYyGnRj5o7qtpJmMl2L69xzUg19zH+qmAJ1BXrkRHgvfdwReupe/PDziMTJDU2Av/eV68WP3C9WH/zDAcVBnU+fueNMmOg0Q2O6qeF0tSz21/KDA82d7Yn+20Zohite4sXOwu026pUsuqxRyuwRU/hauXshwLfTUH8UrlGCscEBhB7D6lKEZ72Yf+5zRzWeW5nP041k9YszAA5xRxt26eq2ACiP4yamxcoGAMKSfzpcyHoW0aIlleLJwfINrU/Q1jjFKaxS0BRf0HUARhHlNdaE9Iurby+BhdX0yhsJfjw1vn68UjdYOUu+oxUMJ7hfXLx8sY6M+8R+mBfCgbgybqIBA/HDbz+Miwa+bSGc1ZN8U49dP2uKcuDRL9H1ANy4mGtP/svGw+hIx1FO3iN4LFMnIHrtsYPzsVem/0S3CdJMVE7pBU8MjZXo1Kl9urcqBZJXYu9xvCa693mGKqmcfz7B1Ce7FXtlL9XPwQseDOU03EQ1DAMVXHDOQ5H7a9OozezM4Pk+3Vsvojg4tnT+R91gKFWKFxiypdF2dpQPsE3C1OQFfm462AEF5LT6mcNueEISmsbVuqKvXD32/KP9jNxdRbQ9sUyIgEbpope2YY7S7SvXgsVOPUFg==
  template:
    metadata:
      creationTimestamp: null
      name: p2p-api-env-secret
      namespace: api
